version: '3.8'

services:
  api:
    build: ./backend
    container_name: nestnet-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nestnet

  frontend:
    build: ./frontend
    container_name: nestnet-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - nestnet

  postgres:
    image: postgres:15
    container_name: nestnet-postgres
    environment:
      POSTGRES_USER: nestnet
      POSTGRES_PASSWORD: nestnet
      POSTGRES_DB: nestnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestnet

volumes:
  pgdata:

networks:
  nestnet:
    driver: bridge